[project]
name = "room"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "folium>=0.19.5",
    "geopy>=2.4.1",
    "selenium>=4.18.1",
    "typer>=0.15.3",
    "webdriver-manager>=4.0.1",
]
